Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -9,8 +9,6 @@ jobs:
           python manage.py check
 
   test:
-    needs:
-      - build
     docker:
       - image: python:3.6
     steps:
@@ -20,8 +18,6 @@ jobs:
           python manage.py test taskManager
 
   integration:
-    needs:
-      - test
     docker:
       - image: python:3.6
     steps:
@@ -29,33 +25,60 @@ jobs:
       - run:
           command: |
             echo "This is an integration step"
-            exit 0
+            exit 1
+          when: on_fail      # Even if the job fails, continue to the next jobs
 
   prod:
-    needs:
-      - integration
     docker:
       - image: python:3.6
     steps:
       - checkout
       - run: echo "This is a deploy step"
-      
+
   artifact:
     docker:
       - image: python:3.6
     steps:
       - checkout
-      - run: |
-          echo "hello" > hello.txt
-    outputs:
-      - name: artifact
-        path: hello.txt
+      - run: echo "hello" > hello.txt
+      - store_artifacts:
+          path: hello.txt
+          destination: artifact-file
 
 workflows:
   version: 2
   django:
     jobs:
-      - build
-      - test
-      - integration
-      - prod
+      - build:
+          filters:          # Run the job with a specific branch
+            branches:
+              only:
+                - main
+      - test:
+          requires:
+            - build
+          filters:
+            branches:
+              only:
+                - main
+      - integration:
+          requires:
+            - test
+          filters:
+            branches:
+              only:
+                - main
+      - prod:
+          requires:
+            - integration
+          filters:
+            branches:
+              only:
+                - main
+      - artifact:
+          requires:
+            - prod
+          filters:
+            branches:
+              only:
+                - main
